connection:
  info:
    ip: 127.0.0.1
    port: 5000
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: examples/data/housing_mlp/random/data_party0.npz
  name: HousingMLPKerasDataHandler
  path: ibmfl.util.data_handlers.housing_mlp_keras_data_handler
fusion:
  name: FedAvgFusionHandler
  path: ibmfl.aggregator.fusion.fedavg_fusion_handler
hyperparams:
  global:
    max_timeout: 60
    num_parties: 10
    rounds: 10
    termination_accuracy: 0.9
  local:
    training:
      batch_size: 1
      epochs: 1
      steps_per_epoch: 1
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
