aggregator:
  ip: 127.0.0.1
  port: 5000
connection:
  info:
    ip: 127.0.0.1
    port: 8087
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: examples/data/housing_mlp/random/data_party2.npz
  name: HousingMLPKerasDataHandler
  path: ibmfl.util.data_handlers.housing_mlp_keras_data_handler
local_training:
  name: FedAvgLocalTrainingHandler
  path: ibmfl.party.training.fedavg_local_training_handler
model:
  name: KerasFLModel
  path: ibmfl.model.keras_fl_model
  spec:
    model_definition: examples/configs/fedavg/keras/compiled_keras.h5
    model_name: keras-cnn
privacy:
  metrics: true
protocol_handler:
  name: PartyProtocolHandler
  path: ibmfl.party.party_protocol_handler
